In [3]:
#numpy basic operation
import numpy as np
my_array = numpy.array([0, 1, 2, 3, 4])


In [3]:
print(my_array)

[0 1 2 3 4]


In [5]:
import numpy as np
my_array = numpy.array([0, 2,4,6])

In [6]:
print (my_array)

[0 2 4 6]


In [7]:
import numpy as np

a_list = [1, 2, 3, 4]
print(a_list)

[1, 2, 3, 4]


In [8]:
import numpy as np

array_A = np.array([1, 2, 3])
array_B = np.array([4, 5, 6])

print(array_A + array_B)

[5 7 9]


In [20]:
import numpy as np

months_array = np.array(['Jan', 'Feb', 'March', 'Apr', 'May'])
print(months_array[3])

Apr


In [22]:
print(months_array[4])

May


In [8]:
# IMPORT numpy as np
import numpy as np

# Lists
prices = [170.12, 93.29, 55.28, 145.30, 171.81, 59.50, 100.50]
earnings = [9.2, 5.31, 2.41, 5.91, 15.42, 2.51, 6.79]

# NumPy arrays
prices_array = np.array(prices)
earnings_array = np.array(earnings)

# Print the arrays
print(prices_array)
print(earnings_array)



[170.12  93.29  55.28 145.3  171.81  59.5  100.5 ]
[ 9.2   5.31  2.41  5.91 15.42  2.51  6.79]


In [9]:
# single dimensional array-

In [10]:

import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [11]:
# multi dimensional array-

In [12]:
a=np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


In [13]:
import numpy as np
 
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
 
print(a[2])

[ 9 10 11 12]


In [14]:
import numpy as np
arr = np.array([1, 2, 3, 4, 6])
print(arr)

[1 2 3 4 6]


In [15]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
print(a[5])


6


In [1]:
#numpy.sort( )
import numpy as np

array = np.array([
    [3, 7, 1],
    [10, 3, 2],
    [5, 6, 7]
])

In [2]:
print(array)
print()

[[ 3  7  1]
 [10  3  2]
 [ 5  6  7]]



In [3]:
# Sort the whole array
print(np.sort(array, axis=None))

[ 1  2  3  3  5  6  7  7 10]


In [4]:
# Sort along each row
print(np.sort(array, axis=1))

[[ 1  3  7]
 [ 2  3 10]
 [ 5  6  7]]


In [5]:
# Sort along each row
print(np.sort(array, axis=1))

[[ 1  3  7]
 [ 2  3 10]
 [ 5  6  7]]


In [6]:
#Using np.mean( )
import numpy as np

list = [
    np.array([3, 2, 8, 9]),
    np.array([4, 12, 34, 25, 78]),
    np.array([23, 12, 67])
]

In [7]:
result = []
for i in range(len(list)):
    result.append(np.mean(list[i]))

In [8]:
print(result)

[5.5, 30.6, 34.0]


In [9]:
#Adding Row using numpy.vstack( )
import numpy as np

array = np.array([
    [3, 2, 8],
    [4, 12, 34],
    [23, 12, 67]
])

In [10]:
newRow = np.array([2, 1, 8])
newArray = np.vstack((array, newRow))
print(newArray)

[[ 3  2  8]
 [ 4 12 34]
 [23 12 67]
 [ 2  1  8]]


In [11]:
#Adding Column using numpy.column_stack( )
import numpy as np

array = np.array([
    [3, 2, 8],
    [4, 12, 34],
    [23, 12, 67]
])

In [13]:
newColumn = np.array([2, 1, 8])
newArray = np.column_stack((array, newColumn))
print(newArray)

[[ 3  2  8  2]
 [ 4 12 34  1]
 [23 12 67  8]]


In [14]:
#Using numpy.flipud( )
import numpy as np

array = np.array([3, 6, 7, 2, 5, 1, 8])
reversedArray = np.flipud(array)

In [15]:
print(reversedArray)

[8 1 5 2 7 6 3]


In [16]:
#Using numpy.dot( )
import numpy as np

matrix1 = [
    [3, 4, 2],
    [5, 1, 8],
    [3, 1, 9]
]

matrix2 = [
    [3, 7, 5],
    [2, 9, 8],
    [1, 5, 8]
]


In [17]:
result = np.dot(matrix1, matrix2)
print(result)

[[19 67 63]
 [25 84 97]
 [20 75 95]]


In [18]:
#Data type
import numpy as np
dt = np.dtype(np.int32)
print (dt)

int32


In [1]:
pip install np

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for np: filename=np-1.0.2-py3-none-any.whl size=13676 sha256=db655c31155d64840448b00e2ab7b407c781e0973e547def9303f415facf0150
  Stored in directory: c:\users\user.desktop-omq89va\appdata\local\pip\cache\wheels\07\8e\38\47fc5b8c6f5d81676d9e662ccac43e20dd5a5ef57efada461b
Successfully built np
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
